@startuml C3_C4
class C3 {
    # protectedBaseField : int
    + publicBaseProperty : string {getter,setter}
    + C3() <<constructor>>
    # ProtectedBaseMethod() : void
    + PublicBaseMethod() : void
}

class C4 {
    - __privateDerivedField : int
    + publicDerivedProperty : string {getter,setter}
    + C4() <<constructor>>
    - __PrivateDerivedMethod() : void
    + PublicDerivedMethod() : void
    + CallBaseProtectedMethod() : void
}

C4 ..|> C3
@enduml