version: "3.9"
name: design_patterns

services:
    postgres:
        image: ${POSTGRES_IMAGE}
        container_name: ${POSTGRES_CONTAINER_NAME}
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - ${POSTGRES_VOLUME}:/var/lib/postgresql
volumes:
    dp_lab4:
        name: ${POSTGRES_VOLUME}
