version: "3.9"

services:
    postgres:
        image: postgres:latest # фиксируем версию — не latest
        container_name: lab4-postgres
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: "111"
        ports:
            - "5432:5432"
        volumes:
            - design_patterns_lab4:/var/lib/postgresql/data

volumes:
    design_patterns_lab4:
